[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Axel Lindeberg <axel.ew.lindeberg@gmail.com>"]
edition = "2018"
default-run = "aoc2020"

[dependencies]
itertools = "0.9"
regex = "1.4"
once_cell = "1.5"
